// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkewjaeehfqfyclyyhlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrZXdqYWVlaGZxZnljbHl5aGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzMjA4MzQsImV4cCI6MjA5MTg5NjgzNH0.al-hYOM9b7L-w7xFUPbDMnHLw0uP_kyLhuJaFRTD4eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});